# Generated by Django 4.2.4 on 2023-08-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_orderposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
